---

- name: Install and configure Nginx
  hosts: web
  become: yes
  roles:
    - nginx

- name: Install Docker and Django application
  hosts: app
  become: yes
  roles:
    - docker
  tasks:
    - name: Copy docker-compose.yml
      template:
        src: inventories/templates/docker-compose.yml.j2
        dest: /opt/django_app/docker-compose.yml
        owner: dnk
        group: dnk
        mode: '0644'

    - name: Build and start containers
      command: docker-compose up -d
      args:
        chdir: /opt/django_app
