---
- name: Install/Configure/Deploy Master db
  hosts: db_master
  become: true
  roles:
    - postgres

- name: Install/Configure/Deploy Slave db
  hosts: db_slave
  become: true
  roles:
    - postgres
